/**
 * Profanity word list for SK/CZ/EN/UK content moderation.
 * Checked as substrings (lowercase) — keep entries short enough
 * to catch inflected forms, but specific enough to avoid false positives.
 *
 * To add words: append to the relevant section and keep sorted.
 */
export const PROFANITY_LIST: readonly string[] = [
  // ── Slovak / Czech ─────────────────────────────────────────────────────────
  'chuj',
  'cipa',
  'čipa',
  'debil',
  'dopica',
  'dosrať',
  'drísť',
  'hajzel',
  'hovno',
  'idiot',
  'jebat',
  'jebať',
  'jebem',
  'jebnutý',
  'kokot',
  'kretén',
  'kunda',
  'kurva',
  'kurvy',
  'mrdat',
  'mrdať',
  'mrdka',
  'pica',
  'piča',
  'picka',
  'píča',
  'píčka',
  'pizdec',
  'pizdos',
  'posrat',
  'posrať',
  'prdel',
  'prdět',
  'prdit',
  'prúser',
  'skurvený',
  'srať',
  'sračka',
  'suka',
  'šulin',
  'vykurvit',
  'vykurviť',
  'zasrať',
  'zajebaný',
  'zkurvený',

  // ── English ─────────────────────────────────────────────────────────────────
  'asshole',
  'bastard',
  'bitch',
  'bullshit',
  'cocksucker',
  'cunt',
  'dickhead',
  'faggot',
  'motherfuck',
  'nigger',
  'pussy',
  'whore',

  // ── Ukrainian / Russian (latin transliteration) ────────────────────────────
  'blyad',
  'bliad',
  'govno',
  'huesos',
  'khuy',
  'pizda',
  'pzdec',
  'suka',
  'zalupa',
  'ebat',
  'yebat',

  // ── Cyrillic (in case user types in Cyrillic) ──────────────────────────────
  'хуй',
  'піздa',
  'пizda',
  'пизда',
  'блядь',
  'бляд',
  'єбать',
  'ебать',
  'сука',
  'говно',
  'залупа',
  'кокот',
  'курва',
];
